-- Don't think i want this

-- return {
-- 	"simrat39/rust-tools.nvim",
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim",
-- 		"mfussenegger/nvim-dap",
-- 	},
-- 	ft = "rust",
-- 	config = function()
-- 		local rt = require("rust-tools")
-- 		rt.setup({
-- 			tools = {
-- 				autoSetHints = true,
-- 				runnables = { use_telescope = true },
-- 				inlay_hints = {
-- 					auto = true,
-- 					show_parameter_hints = true,
-- 				},
-- 				hover_actions = { auto_focus = true },
-- 			},
-- 			server = {
-- 				on_attach = function(_, bufnr)
-- 					vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
-- 					-- Code action groups
-- 					vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })

-- 					vim.api.nvim_create_autocmd({ "BufEnter", "InsertLeave", "BufWritePost", "CursorHold" }, {
-- 						callback = function()
-- 							vim.lsp.codelens.refresh()
-- 						end,
-- 					})

-- 					vim.keymap.set("n", "<leader>cll", function()
-- 						vim.lsp.codelens.run()
-- 					end)
-- 				end,
-- 			},
-- 			dap = {
-- 				adapter = {
-- 					type = "executable",
-- 					command = "lldb-vscode",
-- 					name = "rt_lldb",
-- 				},
-- 			},
-- 		})

-- 		rt.inlay_hints.enable()
-- 	end,
-- }
